import Head from 'next/head';
import {
  Box,
  Divider,
  Grid,
  GridItem,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
  TableContainer,
  Table,
  Thead,
  Th,
  Tr,
  Td,
  Tbody,
  Tfoot,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { Product, Dependency, WalletSection, Form } from '../components';
import { dependencies, products } from '../config';
import { CheckCircleIcon } from '@chakra-ui/icons'

const data = [
  {
    company: 'Twitter',
    title: 'Software Engineer II',
    salary: '50,000',
    gender: 'female',
    age: '26',
    lastPromotion: 'July 2022',
    verified: true,
  },
  {
    company: 'Google',
    title: 'Software Engineer I',
    salary: '35,000',
    gender: 'female',
    age: '26',
    lastPromotion: 'July 2022',
    verified: false,
  },
  {
    company: 'Facebook',
    title: 'Software Engineer',
    salary: '65,000',
    gender: 'female',
    age: '26',
    lastPromotion: 'July 2022',
    verified: true,
  }
]

export default function Dashboard() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
      </Flex>
      <Box mb='30px' textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
          LoopHole Data
        </Heading>
      </Box>
      <TableContainer>
        <Table variant='simple'>
          <Thead>
          <Tr>
              <Th>Company</Th>
              <Th>Title</Th>
              <Th>Salary</Th>
              <Th>Gender</Th>
              <Th>Age</Th>
              <Th>Last Promotion</Th>
          </Tr>
          </Thead>
          <Tbody>
          {/* {data.map((item) => (
            <Tr key={}>
              <Td>{item.company} <CheckCircleIcon color='green'/></Td>
              <Td>Software Engineer I</Td>
              <Td>£52,000</Td>
              <Td>Female</Td>
              <Td>26</Td>
              <Td>July 2022</Td>
            </Tr>
          ))} */}
          <Tr>
              <Td>Twitter <CheckCircleIcon color='green'/></Td>
              <Td>Software Engineer I</Td>
              <Td>£52,000</Td>
              <Td>Female</Td>
              <Td>26</Td>
              <Td>July 2022</Td>
          </Tr>
          <Tr>
              <Td>Facebook</Td>
              <Td>Software Engineer II</Td>
              <Td>£60,000</Td>
              <Td>Female</Td>
              <Td>26</Td>
              <Td>October 2021</Td>
          </Tr>
          <Tr>
              <Td>Google <CheckCircleIcon color='green'/></Td>
              <Td>Software Engineer II</Td>
              <Td>£70,000</Td>
              <Td>Female</Td>
              <Td>26</Td>
              <Td>October 2021</Td>
          </Tr>
          </Tbody>
        </Table>
      </TableContainer>
    </Container>
  );
}
